### ISSUE TITLE
undefined wire

### ISSUE THREAD

**Issue by benamar** [asapach/babel-plugin-rewire-exports#1]
Hello,
I can't make it work!
Here is my .babelrc
{
    "presets": [
        "es2015",
        "stage-0"
    ],
    "plugins": [
        'add-module-exports',
        'transform-decorators-legacy',
        'rewire-exports'
    ]
}

in my test I just add this :
import {rewire,restore} from 'request-promise';
log(rewire)
=> undefined

Please can you tell me what am I doing wrong then?

**Comment by asapach** [comment]
This might be caused by the order of execution of plugins/presets. I'll take a look.

**Comment by asapach** [comment]
@benamar, [`add-module-exports`](https://www.npmjs.com/package/babel-plugin-add-module-exports) plugin is incompatible with `rewire-exports` since it overwrites exports in a different way.

If I reverse the plugin order like this: `['rewire-exports', 'add-module-exports']` it produces the output similar to this one:

``` js
exports.rewire = rewire;
exports.restore = restore;
exports.default = _default;
```

But when I do it your way (`['add-module-exports', 'rewire-exports']`) it changes like this:

``` js
exports.rewire = rewire;
exports.restore = restore;
exports.default = _default;
module.exports = exports['default'];
```

Notice that all exports except `default` are now gone.

I would recommend not mixing the two plugins together.
